/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(
    '/https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/banana/model.gltf'
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_banana.geometry} material={materials.brownDark} />
      <mesh geometry={nodes.Mesh_banana_1.geometry} material={materials.yellow} />
    </group>
  )
}

useGLTF.preload(
  '/https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/banana/model.gltf'
)
